
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\\frame0") #Path(r"C:\Users\dorfe\PycharmProjects\Tkinter-Designer\build\assets\frame0")



def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1273x685")
window.configure(bg = "#F0F0F3")


canvas = Canvas(
    window,
    bg = "#F0F0F3",
    height = 685,
    width = 1273,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    276.0,
    685.0,
    fill="#3A7FF6",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1078.0,
    342.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFA53C",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=883.0,
    y=0.0,
    width=390.0,
    height=683.0
)

canvas.create_text(
    294.0,
    23.0,
    anchor="nw",
    text="Bulls and Hits",
    fill="#745FF2",
    font=("Inter Regular", 48 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    330.0,
    143.05126953125,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=294.0,
    y=108.0,
    width=72.0,
    height=68.1025390625
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    419.5,
    143.05126953125,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=384.0,
    y=108.0,
    width=71.0,
    height=68.1025390625
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    508.5,
    143.05126953125,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=473.0,
    y=108.0,
    width=71.0,
    height=68.1025390625
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    601.0,
    143.05126953125,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=565.0,
    y=108.0,
    width=72.0,
    height=68.1025390625
)

canvas.create_text(
    310.0,
    271.0,
    anchor="nw",
    text="Hits:",
    fill="#FF738E",
    font=("Inter Regular", 32 * -1)
)

canvas.create_text(
    310.0,
    209.0,
    anchor="nw",
    text="Bulls:",
    fill="#FF738E",
    font=("Inter Regular", 32 * -1)
)

canvas.create_text(
    607.0,
    220.0,
    anchor="nw",
    text="matching digits in the right positions",
    fill="#7B0AA3",
    font=("Inter Regular", 15 * -1)
)

canvas.create_text(
    607.0,
    282.0,
    anchor="nw",
    text="matching digits in different positions",
    fill="#7C0AA4",
    font=("Inter Regular", 15 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=295.0,
    y=343.0,
    width=250.0,
    height=70.1025390625
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=13.0,
    y=23.0,
    width=250.0,
    height=70.1025390625
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=13.0,
    y=108.0,
    width=250.0,
    height=70.1025390625
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=13.0,
    y=193.0,
    width=250.0,
    height=70.1025390625
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=14.0,
    y=278.0,
    width=250.0,
    height=70.1025390625
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=295.0,
    y=498.0,
    width=72.0,
    height=70.1025390625
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=564.0,
    y=590.0,
    width=71.0,
    height=70.1025390625
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=654.0,
    y=498.0,
    width=71.0,
    height=70.1025390625
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=654.0,
    y=590.0,
    width=71.0,
    height=70.1025390625
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=294.0,
    y=590.0,
    width=72.0,
    height=70.1025390625
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=384.0,
    y=590.0,
    width=71.0,
    height=70.1025390625
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=386.0,
    y=498.0,
    width=71.0,
    height=70.1025390625
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_13 clicked"),
    relief="flat"
)
button_13.place(
    x=475.0,
    y=498.0,
    width=71.0,
    height=70.1025390625
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_14 clicked"),
    relief="flat"
)
button_14.place(
    x=474.0,
    y=590.0,
    width=71.0,
    height=70.1025390625
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_15 clicked"),
    relief="flat"
)
button_15.place(
    x=564.0,
    y=498.0,
    width=71.0,
    height=70.1025390625
)
window.resizable(False, False)
window.mainloop()
